openapi: 3.0.0
info:
  title: Avito.tech Internship Backend 2022
  description: >-
    Microservice for working with the balance of users.
  contact:
    email: dev@pershin-daniil.ru
  version: 0.0.1
externalDocs:
  description: GitHub
  url: https://github.com/pershin-daniil/internship_backend_2022
servers:
  - url: https://localhost:8080/api/v1
paths:
  /addFunds:
    post:
      tags:
        - methods
      summary: The method of adding funds to the balance. Takes the user id, transaction uuid and how much money to add.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addFundsRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addFundsResponse'
        410:
          description: Gone. Transaction already has been made.

components:
  schemas:
    addFundsRequest:
      type: object
      properties:
        transactionID:
          type: string
          format: uuid
          example: 8333d1d6-57bd-415b-8668-97c4612a772d
        userID:
          type: integer
          format: int
          example: 10
        account_balance:
          type: integer
          format: int
          example: 100
    addFundsResponse:
      type: object
      properties:
        id:
          type: integer
          format: int
          example: 3
        userID:
          type: integer
          format: int
          example: 10
        account_balance:
          type: integer
          format: int
          example: 100
        updatedAt:
          type: string
          format: 'date-time'
          example: '2023-03-27T12:07:33.352266+03:00'